### ISSUE TITLE
unable to call clamda init

### ISSUE THREAD

**Issue by isabelbaskin** [haydenth/clamda#1]
Error when calling `aws-vault exec work -- clamda init`

```es-query-multiple git:(master) ✗ aws-vault exec second -- clamda init
INFO:botocore.credentials:Found credentials in environment variables.
INFO:clamda:initializing new lambda job
INFO:clamda:Looks like a dotfile doesn't exist for this folder, let's instantiate a job...
Traceback (most recent call last):
  File "/usr/local/bin/clamda", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/clamda.py", line 247, in main
    make_new_lambda_function()
  File "/usr/local/lib/python3.7/site-packages/clamda.py", line 59, in make_new_lambda_function
    role_data = iam_client.list_roles()
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 586, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the ListRoles operation: The security token included in the request is invalid
```

Other clamda calls are working (`clamda deploy`) other aws calls are working (so not an aws-vault issue, it is authenticating directly).

**Comment by haydenth** [comment]
Looking at this now. i wonder if it has something to do with the call to fetch roles from aws

```
  # get roles
  role_data = iam_client.list_roles()
  available_roles = role_data['Roles']
```

it's weird that its saying invalid token tho

**Comment by haydenth** [comment]
Looks like this is not unique to clamda:
https://github.com/99designs/aws-vault/issues/266

Looking...

**Comment by haydenth** [comment]
I have a suspicion this may have to do with the role you are assuming inside the aws-vault. I will send you a DM @isabelbaskin

**Comment by haydenth** [comment]
I refer the user to:
https://github.com/99designs/aws-vault/blob/master/USAGE.md#not-using-session-credentials
